### ISSUE TITLE
ReferenceError: module is not defined in ES module scope

### ISSUE THREAD

**Issue by grubino** [pamelafox/ndjson-readablestream#5] opened 2023-12-04 14:59 UTC
Hello!  I'm working on a project that depends on ndjson-readablestream and I'm getting this error which apparently is caused by the name of the main package:

`dist/ndjson-readablestream.cjs.js`

Which is odd, because it only shows up when I run my tests (vitest).  If I rename `ndjson-readablestream.cjs.js` => `nsjson-readablestream.cjs` and update the reference in `package.json`, then the error goes away.  I'm not really an expert on ES <=> CJS interoperability, but I really hope there is a better solution for this.

**Comment by pamelafox** [comment] 2023-12-06 19:48
Huh, I am also not an expert in CJS, but I'll ask around, thanks for filing!

**Comment by pamelafox** [comment] 2023-12-20 15:00
@grubino I think I've resolved this, can you try the alpha?

npm install ndjson-readablestream@1.1.0-alpha.0

**Comment by psd-coder** [comment] 2024-01-12 13:01
I can confirm that this alpha version works for me

**Comment by pamelafox** [comment] 2024-01-12 15:23
Thanks! I've released as non-alpha. Closing this now as fixed by https://github.com/pamelafox/ndjson-readablestream/pull/7

**Closed by pamelafox** 2024-01-12 15:23 UTC
